[mysqldb]
host = "127.0.0.1"
user = "adam"
port = 3306
database = "starwarsDB"
password = "qwerty@123"

[swapi]
home_url = "https://swapi.dev"
vehicle = "/api/vehicles"
starship = "/api/starships"
film = "/api/films"
